[[redirects]]
  from = "https://luispeguero.netlify.app/*"
  to = "https://luispeguerojr.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://luispeguerojr.com/*"
  to = "https://luispeguerojr.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
